### ISSUE TITLE
Uncaught TypeError: Cannot read property 'jQuery1495146417417' of null

### ISSUE THREAD

**Issue by espot** [Geta/404handler#37] opened 2017-05-18 22:35 UTC
When pressing the "Show redirects" checkbox I get the following error in the javascript console:

DojoDashboardCompatibility.js:1 Uncaught TypeError: Cannot read property 'jQuery1495146417417' of null
    at Function.data (DojoDashboardCompatibility.js:1)
    at init.delegate (DojoDashboardCompatibility.js:6)
    at HTMLFormElement.<anonymous> (DojoDashboardCompatibility.js:7)
    at HTMLFormElement.handle (DojoDashboardCompatibility.js:2)
    at HTMLFormElement.<anonymous> (DojoDashboardCompatibility.js:1)

using EPiServer.CMS 10.9.1 and BVN.404Handler 10.1.1

**Comment by marisks** [comment] 2018-02-09 08:16
I am not able to reproduce this.  Do you have this issue in all your projects or just one?

**Comment by marisks** [comment] 2018-03-05 15:12
Closing as no updates on this.

**Closed by marisks** 2018-03-05 15:12 UTC
Labels: bug
